config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "events#index"
  get 'my_groups', to: 'groups#my_groups', as: :my_groups

  resources :groups do
    resources :group_participants
    resources :events
  end

  resources :events, only: [:index, :show] do
    collection do
      get 'search'
    end
    resources :event_participants, as: 'participants'
    post 'events/:event_id/event_participants', to: 'event_participants#create', as: 'event_event_participants'
    delete '/events/:event_id/event_participants/:id', to: 'event_participants#destroy'
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  get 'about', to: 'pages#about'
  get 'terms-and-conditions', to: 'pages#tandc'
  get 'privacy-policy', to: 'pages#private'
  get 'contact-us', to: 'pages#contact'
  get 'cookies-policy', to: 'pages#cookies'



  resources :users, only: [] do
    resources :workout_preferences
    post 'generate_workout_plan', to: 'workout_preferences#generate_workout_plan'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :events, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
    @group_participants = GroupParticipant.all
    @my_groups = GroupParticipant.where(user_id: current_user.id).map(&:group) + Group.where(user_id: current_user.id)
    # GroupParticipant.all.where(group_id: @group.id) 
  end

  def my_groups
    @my_groups = GroupParticipant.where(user_id: current_user.id).map(&:group) + Group.where(user_id: current_user.id)
  end

  def show
    @group = Group.find(params[:id])
    @events = @group.events
    #    @admin = User.where(@event)
    #    @admin = Group.find(params[:id]).user
    @group_participant = GroupParticipant.new
    @group_participants = GroupParticipant.where(group_id: @group.id)
    @existing_participant = @group_participants.find_by(user_id: current_user.id)
    @group_participant_count = @group_participants.count
    @event_participant = EventParticipant.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    # Upload images to Cloudinary and associate their URLs with the yacht
    @group.group_image = Cloudinary::Uploader.upload(params[:group][:group_image].tempfile)

    if @group.save!
      redirect_to groups_path
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.user_id == current_user.id
      if @group.destroy
        redirect_to groups_path, notice: "You have deleted the group."
      else
        redirect_to groups_path, alert: "Failed to delete the group."
      end
    else
      redirect_to groups_path, alert: "You are not authorized to delete this group."
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :city, :group_image)
  end
end

app/views/groups/index.html.erb
<div id="group-index-all" >

  <div id="group-index-above-group-section">
    <div id="group-index-above-group-section-hi-username">
    <h1 id= "group-index-group-section-group-image-h2">Hi <%= current_user.name %> ! <i class="fa-sharp fa-solid fa-heart-pulse fa-beat fa-sm"></i>
    </div>
    <div id="group-index-above-group-section-buttons">
      <div id="group-index-above-group-left-section-buttons">
          <div class="button-container">
                <a href="/groups" class="secondary-squads-button">ALL SQUADS</a>
                  <div class="black-border-effect"></div>
          </div>
        <% if @my_groups.present? %>
            <div class="button-container">
              <a href="/my_groups" class="main-squads-button">MY SQUADS</a>
                  <div class="black-border-effect"></div>
            </div>
        <% end %>
      </div>
      <div class="action-button">
        <div id="group-index-above-group-right-section-buttons">
          <div class="button-container">
          <a href="/groups/new" class="action-button">CREATE SQUAD</a>
            <div id="create-squad-border" class="white-border-effect"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

    <hr id="group-index-above-group-section-buttons-line-break" >


    <div id="group-index-group-section">
        <% @groups.each_with_index do |group, index| %>
        <%@group_participants = GroupParticipant.where(group_id: group.id)%>
        <%@existing_participant = @group_participants.find_by(user_id: current_user.id)%>
        <div style="display: flex;">
          <div id="group-index-group-section-group-image-and-name">
          <div id="group-index-avatars-and-join-button">
            <div id="group-index-group-section-group-avatars">
              <%@group_participants.each do |participant| %>
                <%if participant.user.avatar.nil?%>
                  <%= image_tag "blank_avatar.jpg" %>
                  <p class="hide"><%=participant.user.name%></p>
                <%else%>
                  <%= image_tag participant.user.avatar %>
                  <p class="hide"><%=participant.user.name %></p>
                <% end %>
              <% end %>   
              </div>     
          </div>         

          <div style="display: flex; flex-direction: row-reverse; min-width: fit-content;"> 
          <div id="group-index-group-section-group-name">
          <h2> <%=group.name%> </h2>
          <h4> <%=group.city%> </h4>
            <%if group &&  group.user_id == current_user.id %>
              <%= link_to 'You are the Squad leader', group_path(group) %>
            <%else%>
              <div class="more-details" id="groups-details">
                <%= link_to 'More Details', group_path(group) %>
              </div>                 
            <% end %>
          </div>
            <% if group.group_image.end_with?("jpg") %>
              <%= image_tag group.group_image %>
            <% else %>
              <%= image_tag eval(group.group_image)["url"]%>
          </div>
        <% end %>
        </div>
      </div>
    </div>

      
      <div id="group-index-group-section-event-image">
        <% group.events.take(5).each do |event| %>
<div class="group-index-event-card">
    <%# front of the card %>
<% if event.event_image.end_with?("jpg") %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url(event.event_image) %>)">
      <% else %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url eval(event.event_image)["secure_url"] %>)">
      <%end%>
        <h1 class="card-address"><i class="fa">&#xf041;</i>
          <% if event.address.present? %>
            <% first_line_of_address = event.address.split(',')[0].strip if event.address %>
            <%= first_line_of_address %>
          <% else %>
            Address not available
          <% end %>
        </h1>
        <h1 class="event-card-title">
          <%= event.name %>
        </h1>
        <h2 class="card-time-date">
          <% date = event.date %>
          <% time = event.time %>
          <%= Time.parse(date.strftime("%Y-%m-%d")).strftime("%d/%m/%y") %>,
          <%= Time.parse(time.strftime("%I:%M%P")).strftime("%I:%M%P") %>
        </h2>

        <%# back of the card %>
        <div class="card-back">

            <div class="event-card-host">
            <%if event.group.user.avatar.nil? %>
              <%= image_tag "blank_avatar.jpg", class: "avatar", style: "width: 50px; height: 50px;"%>
            <%else%>
              <%= image_tag event.group.user.avatar, class: "avatar", style: "width: 50px; height: 50px;" %>
            <%end%>
              Hosted by <strong> <%= event.group.user.name%> </strong>
            </div>
          <br>
            <h3 class="event-card-title-back"><%= event.name %></h3>
          <br>
          <div class="event-card-description-box">
            <p class="event-card-description">
              <%= event.description  %>
            </p>
          </div>
                <div class="event-card-participants">
                  <p><%= event.event_participants.count%> Squad members</p>
                </div>
          <a class="card-join-button" href="<%= group_event_path(event.group_id, event.id) %>">more details</a>
          <a class="card-join-button" href="#">Join</a>
        </div>

      </div>
  </div>
<% end %>
        <div id="events-scroll-button">
        <%if group.events.empty?%>
        <h2> No Events... Please search again!</h2>
        <% else %>
        <button style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.5)80%)"><%= link_to 'More Events', group_path(group) %></button>
        <% end %>
        </div>
        </div>
      <hr >
    <% end %>       

</div>
</div>

app/views/groups/my_groups.html.erb
<div id="group-index-all" >

  <div id="group-index-above-group-section">
    <div id="group-index-above-group-section-hi-username">
    <h1 id= "group-index-group-section-group-image-h2">Hi <%= current_user.name %>! <i class="fa-sharp fa-solid fa-heart-pulse fa-beat fa-sm"></i>
    </div>
    <div id="group-index-above-group-section-buttons">
      <div id="group-index-above-group-left-section-buttons">
          <div class="button-container">
            <a href="/groups" class="secondary-squads-button">ALL SQUADS</a>
            <div class="black-border-effect"></div>          
          </div>
        <% if @my_groups.present? %>
            <div class="button-container">
              <a href="/my_groups" class="main-squads-button">MY SQUADS</a>
              <div class="black-border-effect"></div>
            </div>
        <% end %>
      </div>
      <div class="action-button">
        <div id="group-index-above-group-right-section-buttons">
          <div class="button-container">
          <a href="/groups/new" class="action-button">CREATE SQUAD</a>
            <div id="create-squad-border" class="white-border-effect"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

    <hr id="group-index-above-group-section-buttons-line-break" >


    <div id="group-index-group-section">
        <% @my_groups.each_with_index do |group, index| %>
        <%@group_participants = GroupParticipant.where(group_id: group.id)%>
        <%@existing_participant = @group_participants.find_by(user_id: current_user.id)%>
        <div style="display: flex;">
          <div id="group-index-group-section-group-image-and-name">
          <div id="group-index-avatars-and-join-button">
            <div id="group-index-group-section-group-avatars">
              <%@group_participants.each do |participant| %>
                <%if participant.user.avatar.nil?%>
                  <%= image_tag "blank_avatar.jpg" %>
                  <p class="hide"><%=participant.user.name%></p>
                <%else%>
                  <%= image_tag participant.user.avatar %>
                  <p class="hide"><%=participant.user.name %></p>
                <% end %>
              <% end %>   
              </div>     
          </div>         

          <div style="display: flex; flex-direction: row-reverse;"> 
          <div id="group-index-group-section-group-name">
          <h2> <%=group.name%> </h2>
          <h4> <%=group.city%> </h4>
            <%if group &&  group.user_id == current_user.id %>
              <%= link_to 'You are the Squad leader', group_path(group) %>
            <%else%>
              <div class="more-details" id="groups-details">
                <%= link_to 'More Details', group_path(group) %>
              </div>          
          <% end %>
          </div>
            <% if group.group_image.end_with?("jpg") %>
              <%= image_tag group.group_image %>
            <% else %>
              <%= image_tag eval(group.group_image)["url"]%>
          </div>
        <% end %>
        </div>
      </div>
    </div>

      
      <div id="group-index-group-section-event-image">
        <% group.events.take(5).each do |event| %>
<div class="group-index-event-card">
    <%# front of the card %>
<% if event.event_image.end_with?("jpg") %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url(event.event_image) %>)">
      <% else %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url eval(event.event_image)["secure_url"] %>)">
      <%end%>
        <h1 class="card-address"><i class="fa">&#xf041;</i>
          <% if event.address.present? %>
            <% first_line_of_address = event.address.split(',')[0].strip if event.address %>
            <%= first_line_of_address %>
          <% else %>
            Address not available
          <% end %>
        </h1>
        <h1 class="event-card-title">
          <%= event.name %>
        </h1>
        <h2 class="card-time-date">
          <% date = event.date %>
          <% time = event.time %>
          <%= Time.parse(date.strftime("%Y-%m-%d")).strftime("%d/%m/%y") %>,
          <%= Time.parse(time.strftime("%I:%M%P")).strftime("%I:%M%P") %>
        </h2>

        <%# back of the card %>
        <div class="card-back">

            <div class="event-card-host">
            <%if event.group.user.avatar.nil? %>
              <%= image_tag "blank_avatar.jpg", class: "avatar", style: "width: 50px; height: 50px;"%>
            <%else%>
              <%= image_tag event.group.user.avatar, class: "avatar", style: "width: 50px; height: 50px;" %>
            <%end%>
              Hosted by <strong> <%= event.group.user.name%> </strong>
            </div>
          <br>
            <h3 class="event-card-title-back"><%= event.name %></h3>
          <br>
          <div class="event-card-description-box">
            <p class="event-card-description">
              <%= event.description  %>
            </p>
          </div>
                <div class="event-card-participants">
                  <p><%= event.event_participants.count%> Squad members</p>
                </div>
          <a class="card-join-button" href="<%= group_event_path(event.group_id, event.id) %>">more details</a>
          <a class="card-join-button" href="#">Join</a>
        </div>

      </div>
  </div>
<% end %>
        <div id="events-scroll-button">
        <%if group.events.empty?%>
        <h2> No Events... Please search again!</h2>
        <% else %>
        <button style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.5)80%)"><%= link_to 'More Events', group_path(group) %></button>
        <% end %>
        </div>
        </div>
      <hr >
    <% end %>       

</div>
</div>

app/views/groups/new.html.erb
<div class="container my-4 my-md-5">
<h1>Squad Creation form</h1>
  <div class="row align-items-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <%= simple_form_for [@group], html: { class: 'form' } do |form| %>
            <% if @group.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
                <ul>
                  <% @group.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
                <%= form.input :name, placeholder: 'e.g. Tom and friends Basketball Group ', class: 'form-control'%>
            </div>

            <div class="form-group">
              <%= form.input :city, placeholder: 'e.g. London', class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.input :group_image, as: :file, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :Description %>
              <%= form.text_area :description, rows: 8, placeholder: 'e.g. Welcome to my Basketball group for all expierence levels...', class: 'form-control' %>
            </div>

            <div class="form-actions text-center">
              <%= form.submit "Create Squad", class: 'btn btn-primary', style: " margin-top: 10px; width: -webkit-fill-available; "%>
            </div>
        
        </div>
      </div>
    </div>

    <!-- Second container -->
    <div class="col-md-6">

          <br>
            <div class="col-md-6 mx-auto">
      <div class="card mb-4">
        <div class="card-body">
          <h4 class="card-text"> Tips </h4>
          <p class="card-text"> - Make the squad name short and memorable </p>
          <p class="card-text"> - Have a good description about the squad and it's events  </p>
          <p class="card-text"> - Make sure the image is a good resolution  </p>
        </div>
      </div>
    </div>
      <br>
    <!-- Box 2 -->
    <div class="col-md-6 mx-auto">
      <div class="card mb-4">
        <div class="card-body">
          <h4 class="card-text"> Description example </h4>
          <p class="card-text"> " Hello this a basketball group where i will set events for basketball around east london for anyone to come and join in on the fun... "    </p>
        </div>
      </div>
    </div>
  </div>

        <% end %>


      <!-- Your content for the second container goes here -->
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<%# page container %>
<div id="group-show-container">
  <%# left side of page %>
  <div id="group-show-left-side">
    <%# top left side %>
    <%# group image and description%>
    <div>
      <div id="group-show-left-side-image-and-description">
        <% if @group.group_image.end_with?("jpg") %>
          <%= image_tag @group.group_image  %>
        <%else%>
          <%= image_tag eval(@group.group_image)["url"] %>
          <p> </p>
        <% end %>
        <div id="group-show-left-image-and-title">
      <h1 style="color:light-grey;"><%= @group.name %></h1>
      <strong></strong>
      </div>
      </div>
      <div id="group-show-left-side-button">
      <%= render partial: 'group_participants/form', locals: { group: @group } %>
      </div>
        <h5> <%= @group.description  %></h5>
    <%# bottom left side, squad members %>
    <div>
    </div>
  </div>
  
  </div>

  <%# right side of page %>
  <div id="group-show-rigth-side">
  <%# squad info %>
    <div id="group-show-rigth-side-squad-info">
      <%if @group.user.avatar.nil?%>
        <h2><%= image_tag "blank_avatar.jpg", style: "margin: 4px;", class: "avatar-bordered" %> Squad Admin <%= @group.user.name %>  </h2> 
      <%else%>
        <h2><%=image_tag  @group.user.avatar, style: "margin: 4px;", class: "avatar-bordered" %> Squad Admin <%= @group.user.name %>  </h2>
      <% end %>
      <%# Squad memvers and join button %>
      <div id="group-show-left-side-members-and-button">
        <% if @group.user_id != current_user.id %>
          <h4>Squad Members</h4>
        <% end %>
      </div>
      <div id="group-right-side-avatars">
      <%# participant avatars %>
      <% @group_participants.each do |participant| %>
        <%if participant.user.avatar.nil?%>
          <%= image_tag "blank_avatar.jpg", style: "margin: 4px;", class: "avatar"%>
        <%else%>
          <%= image_tag participant.user.avatar,style: "margin: 4px;", class: "avatar" %>
        <% end %>
      <% end %>
      </div>
    </div>
  
  <%# event cards %>
    <div id="group-show-event-cards-grid">
    <%= render partial: 'events/display', locals: { group: @group } %></div>
    </div>

</div>