config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "events#index"
  get 'my_groups', to: 'groups#my_groups', as: :my_groups

  resources :groups do
    resources :group_participants
    resources :events
  end

  resources :events, only: [:index, :show] do
    collection do
      get 'search'
    end
    resources :event_participants, as: 'participants'
    post 'events/:event_id/event_participants', to: 'event_participants#create', as: 'event_event_participants'
    delete '/events/:event_id/event_participants/:id', to: 'event_participants#destroy'
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  get 'about', to: 'pages#about'
  get 'terms-and-conditions', to: 'pages#tandc'
  get 'privacy-policy', to: 'pages#private'
  get 'contact-us', to: 'pages#contact'
  get 'cookies-policy', to: 'pages#cookies'



  resources :users, only: [] do
    resources :workout_preferences
    post 'generate_workout_plan', to: 'workout_preferences#generate_workout_plan'
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container-fluid" style=" background-color: black; display: flex; justify-content: space-around; min-height: 60px; height: 60px; align-items: center; margin-top: 10%;">

  <%= link_to 'About us', about_path, class: 'text-white', style: "text-decoration: none;" %>
  <%= link_to 'Contact', contact_us_path, class: 'text-white', style: "text-decoration: none;" %>
  <%= link_to 'Cookies and Policy', cookies_policy_path, class: 'text-white', style: "text-decoration: none;" %>
  <%= link_to 'Privacy Policy', privacy_policy_path, class: 'text-white', style: "text-decoration: none;" %>
<%= link_to 'Terms and Conditions', terms_and_conditions_path, class: 'text-white', style: "text-decoration: none;" %>


  </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-black">
  <div class="container-grid">
    <!-- Logo -->
    <a class="fit-squad-home" href="/">
        <div class="logo-container">
          <img class="logo-image" alt="Logo" src="/assets/fit-squad-logo-07973b0128b31f6f49bbaa2ee31a5d198ece46247c36906e68e174ddca12408f.jpg">            
          <div class="border-effect"></div> <!-- Additional div for border effect -->
        </div>
    </a>


    <!-- Search Bar -->
    <div class="nav-search-bar">
      <%# <div class="d-flex flex-grow-1 justify-content-center"> %>
      <!-- Search Bar -->
        <%= form_with url: search_events_path, method: :get, class: "d-flex" do |form| %>
          <div class="input-group">
            <%= form.text_field :query,
                  class: "form-control custom-search-input",
                  placeholder: "Search for events..."
              %>
            <div class="input-group-append">
              <%= form.submit "Search", class: "btn btn-primary custom-search-button" %>
            </div>
          </div>
        <% end %>
      <%# </div> %>
    </div>

    <!-- Navigation Options -->
    <%# <div class="collapse navbar-collapse" id="navbarNav"> %>
      <%# <ul class="navbar-nav"> %>
        <%# <li class="nav-item custom-dropdown"> <!-- Added 'custom-dropdown' class for custom dropdown --> %>

          <%# <a href="#" class="bb_button bb_button--side-ver nav-link"><span class="bb_button__text">Squads</span></a>  %>
          <%# <div class="custom-dropdown-content"> <!-- Custom dropdown content --> %>
            <%# <a class="nav-link" href="<#%= groups_path%#>">All Squads</a> %>
            <%# <a class="nav-link" href="<#%= my_groups_path%#>">My Squads</a> %>
            <%# need to add link to page showing all squads user is a member of %>
            <%# <a class="nav-link" href="<3%= new_group_path%#>">Create Squad</a> %>
          <%# </div> %>
        <%# </li> %>

        <nav class="menu">
          <ul class="dropdown-container">
            <li class="dropdown dropdown-2 bb_button bb_button--side-ver">
              <a href="#" class="bb_button__text"><span>Squads</span></a> 
              <ul class="dropdown_menu dropdown_menu-2">
                <li class="dropdown_item-1"><a class="nav-link" href="<%= groups_path%>">All Squads</a></li>
                <li class="dropdown_item-2"><a class="nav-link" href="<%= my_groups_path%>">My Squads</a></li>
                <li class="dropdown_item-3"><a class="nav-link" href="<%= new_group_path%>">Create Squad</a></li>
            </li>
          </ul>
            
            <% if user_signed_in? %>

            <li class="dropdown dropdown-2 bb_button bb_button--side-ver">
              <a href="#" class="bb_button__text"><span>Workouts</span></a> 
              <ul class="dropdown_menu dropdown_menu-2">
                <li class="dropdown_item-1"><a target="_blank" class="nav-link" href="<%= new_user_workout_preference_path(current_user) %>">New Workout</a></li>
                <li class="dropdown_item-2"><a class="nav-link" href="<%= user_workout_preferences_path(current_user) %>">View Saved Workouts</a></li>
              </ul>
            </li>
          </ul>
        </nav>

      <div class="navbar-avatar">
          <li class="user-avatar nav-item custom-dropdown"> <!-- Added 'custom-dropdown' class for custom dropdown -->
            <div class="">
              <%if current_user.avatar.nil?%>
                <%= image_tag "blank_avatar.jpg", style: "margin: 4px;", class: "avatar-bordered"%>
              <%else%>
                <%= image_tag current_user.avatar,style: "margin: 4px;", class: "avatar-bordered" %>
              <% end %>          
            </div>
          <div class="custom-dropdown-content"> <!-- Custom dropdown content -->
            <a class="nav-link" href="<%= user_workout_preferences_path(current_user) %>">My Workouts</a>
            <a class="nav-link" href="<%= my_groups_path %>">My Squads</a>
            <a class="nav-link" href="<%= user_workout_preferences_path(current_user) %>">My Events</a>
            <a class="nav-link" href="<%= edit_user_registration_path %>">Edit Account Details</a>
            <a class="nav-link" href="<%= destroy_user_session_path %>" data-turbo-method="delete">Log out</a>
          </div>
        </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
          </li>
        <% end %>
      </div>
      <%# </ul> %>
    <%# </div> %>
  </div>
</nav>