config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "events#index"
  get 'my_groups', to: 'groups#my_groups', as: :my_groups

  resources :groups do
    resources :group_participants
    resources :events
  end

  resources :events, only: [:index, :show] do
    collection do
      get 'search'
    end
    resources :event_participants, as: 'participants'
    post 'events/:event_id/event_participants', to: 'event_participants#create', as: 'event_event_participants'
    delete '/events/:event_id/event_participants/:id', to: 'event_participants#destroy'
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  get 'about', to: 'pages#about'
  get 'terms-and-conditions', to: 'pages#tandc'
  get 'privacy-policy', to: 'pages#private'
  get 'contact-us', to: 'pages#contact'
  get 'cookies-policy', to: 'pages#cookies'



  resources :users, only: [] do
    resources :workout_preferences
    post 'generate_workout_plan', to: 'workout_preferences#generate_workout_plan'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :time, presence: true
  validates :activity, presence: true
  include PgSearch::Model

  pg_search_scope :search_by_name_and_address,
    against: [:name, :address],
    using: {
      tsearch: { prefix: true }
    }

  pg_search_scope :search_by_activity_name,
    associated_against: {
      activity: [:name] # Assuming 'name' is the attribute in the 'Activity' model you want to search against
    }

  multisearchable against: [:name, :address]
  belongs_to :group
  belongs_to :activity
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one :chatroom, dependent: :destroy  # Ensure the chatroom is destroyed when the event is deleted
  has_many :event_participants, dependent: :destroy
  after_create :create_associated_chatroom



  private

  def create_associated_chatroom
    chatroom = Chatroom.create(name:)
    update(chatroom:)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.includes(:event_participants).all
    @event_participant = EventParticipant.new
    date = params[:date]

    # Check if the date is present
    if date.present?
      # The date is present, so filter the events by date
      @events = @events.where(date:)
    else
      # The date is not present, so do not filter the events
      @events = Event.all
    end

    # The `geocoded` scope filters only flats with coordinates
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { event: })
      }
    end
  end

  def show
    @event = Event.find(params[:id])
    @group = @event.group
    # @admin = User.where(@event)
    @event_participant = EventParticipant.new
    @event_participants = EventParticipant.where(event_id: @event.id)
    @existing_participant = @event_participants.find_by(user_id: current_user.id)
    @event_participant_count = @event_participants.count
    @chatroom = @event.chatroom
    # @chatroom.name = @event.name
    @message = Message.new
    @message.chatroom = @chatroom
    @markers = [
      {
        lat: @event.latitude,
        lng: @event.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { event: @event })
        # marker_html: render_to_string(partial: "marker")
      }
    ]
  end

  def new
    @group = Group.find(params[:group_id])
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.event_image = Cloudinary::Uploader.upload(params[:event][:event_image].tempfile)
    @event.group = Group.find(params[:group_id])
    if @event.save
      redirect_to group_event_path(@event.group, @event)
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def search
    @query = params[:query]
    @name_and_address_results = Event.search_by_name_and_address(@query) if @query.present?
    @activity_results = Event.search_by_activity_name(@query) if @query.present?
    @events = (@name_and_address_results || []) + (@activity_results || [])
    @event_participant = EventParticipant.new
    # @events = Event.includes(:event_participants).all
    # @event_participant = EventParticipant.new
    # date = params[:date]
    # Check if the date is present
    # if date.present?
      # The date is present, so filter the events by date
    #   @events = @events.where(date:)
    # else
      # The date is not present, so do not filter the events
      # @events = Event.all
    # end

    # The `geocoded` scope filters only flats with coordinates
    # @markers = @events.geocoded.map do |event|
    #   {
    #     lat: event.latitude,
    #     lng: event.longitude,
    #     info_window_html: render_to_string(partial: "info_window", locals: { event: })
    #   }
    # end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :address, :date, :time, :event_image, :group_id, :activity_id)
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_display.html.erb
<% @events.each do |event| %>
<% if EventParticipant.exists?(user_id: current_user.id, event_id: event.id) %>

  <div class="event-card">
  <%# front of the card %>
    <% if event.event_image.end_with?("jpg") %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url(event.event_image) %>)">

    <% else %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url eval(event.event_image)["secure_url"] %>)">
    <%end%>

            <% if event.address.present? %>
              <div class="card-address-wrapper">
                <h1 class="card-address"><i class="fa">&#xf041;</i>
                  <% first_line_of_address = event.address.split(',')[0].strip if event.address %>
                  <%= first_line_of_address %>
              </h1>
              </div>
            <% else %>
              <p> </p>
            <% end %>

        <h1 class="event-card-title">
          <%= event.name %>
        </h1>

        <h2 class="card-time-date">
          <% date = event.date %>
          <% time = event.time %>
          <%= Time.parse(date.strftime("%Y-%m-%d")).strftime("%d/%m/%y") %>,
          <%= Time.parse(time.strftime("%I:%M%P")).strftime("%I:%M%P") %>
        </h2>
          <%# back of the card %>
            <div class="card-back">

              <h3 class="event-card-host">
                <%if event.group.user.avatar.nil? %>
                  <%= image_tag "blank_avatar.jpg", class: "avatar"%>
                <%else%>
                  <%= image_tag event.group.user.avatar, class: "avatar" %>
                <%end%>
                  Hosted by <strong> <%= event.group.user.name%> </strong>
              </h3>

              <h3 class="event-card-title-back"><%= event.name %></h3>

              <div class="event-card-description-box">
                <p class="event-card-description">
                  <%= event.description  %>
                </p>
              </div>

              <div class="event-card-participants">
                <%= event.event_participants.count%> squad members
              </div>

              <div class="event-card-buttons">
              <div class="button-container" id="events-joined">
                <a href="<%= group_event_path(event.group_id, event.id) %>"><i class="fa-sharp fa-solid fa-heart-pulse fa-beat fa-sm" id="events-card-heart"></i>Joined</a>
                <div class="black-border-effect" id="events-join-border"></div>
              </div>
                <a class="more-details" id="event-more-details"  href="<%= group_event_path(event.group_id, event.id) %>">more details</a>
              </div>

            </div>
        </div>
  </div>



<% else %>
  <%# This is the join event button form  %>
    <%= form_for [event, event, @event_participant] do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id, class: 'card-join-hidden' %>
    <%= f.hidden_field :event_id, value: event.id, class: 'card-join-hidden' %>


  <div class="event-card">
  <%# front of the card %>
    <% if event.event_image.end_with?("jpg") %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url(event.event_image) %>)">

    <% else %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url eval(event.event_image)["secure_url"] %>)">
    <%end%>

            <% if event.address.present? %>
              <div class="card-address-wrapper">
                <h1 class="card-address"><i class="fa">&#xf041;</i>
                  <% first_line_of_address = event.address.split(',')[0].strip if event.address %>
                  <%= first_line_of_address %>
              </h1>
              </div>
            <% else %>
              <p> </p>
            <% end %>

        <h1 class="event-card-title">
          <%= event.name %>
        </h1>

        <h2 class="card-time-date">
          <% date = event.date %>
          <% time = event.time %>
          <%= Time.parse(date.strftime("%Y-%m-%d")).strftime("%d/%m/%y") %>,
          <%= Time.parse(time.strftime("%I:%M%P")).strftime("%I:%M%P") %>
        </h2>

        <%# back of the card %>
            <div class="card-back">

              <h3 class="event-card-host">
                <%if event.group.user.avatar.nil? %>
                  <%= image_tag "blank_avatar.jpg", class: "avatar"%>
                <%else%>
                  <%= image_tag event.group.user.avatar, class: "avatar" %>
                <%end%>
                  Hosted by <strong> <%= event.group.user.name%> </strong>
              </h3>

              <h3 class="event-card-title-back"><%= event.name %></h3>

              <div class="event-card-description-box">
                <p class="event-card-description">
                  <%= event.description  %>
                </p>
              </div>

              <div class="event-card-participants">
                <%= event.event_participants.count%> squad members
              </div>

              <div class="event-card-buttons">
              <div type="submit" class="button-container">
              <div class="main-squads-button" id="events-join">
                <i class="fa-sharp fa-solid fa-heart-pulse fa-beat fa-sm" id="events-card-heart"></i>Join
                <div class="black-border-effect" id="events-join-border"></div>
              </div>
              </div>
                <a class="more-details" id="event-more-details"  href="<%= group_event_path(event.group_id, event.id) %>">more details</a>
              </div>

            </div>
      </div>
  </div>
      <% end %>
<% end %>
<% end %>

app/views/events/_info_window.html.erb
<% if EventParticipant.exists?(user_id: current_user.id, event_id: event.id) %>

  <div class="event-card" style= "height: 280px; width: 280px; font-size: 28px;">
  <%# front of the card %>
    <% if event.event_image.end_with?("jpg") %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url(event.event_image) %>)">

    <% else %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url eval(event.event_image)["secure_url"] %>)">
    <%end%>

            <% if event.address.present? %>
              <div class="card-address-wrapper">
                <h1 class="card-address"><i class="fa">&#xf041;</i>
                  <% first_line_of_address = event.address.split(',')[0].strip if event.address %>
                  <%= first_line_of_address %>
              </h1>
              </div>
            <% else %>
              <p> </p>
            <% end %>

        <h1 class="event-card-title">
          <%= event.name %>
        </h1>

        <h2 class="card-time-date">
          <% date = event.date %>
          <% time = event.time %>
          <%= Time.parse(date.strftime("%Y-%m-%d")).strftime("%d/%m/%y") %>,
          <%= Time.parse(time.strftime("%I:%M%P")).strftime("%I:%M%P") %>
        </h2>
          <%# back of the card %>
            <div class="card-back">

              <h3 class="event-card-host">
                <%if event.group.user.avatar.nil? %>
                  <%= image_tag "blank_avatar.jpg", class: "avatar"%>
                <%else%>
                  <%= image_tag event.group.user.avatar, class: "avatar" %>
                <%end%>
                  Hosted by <strong> <%= event.group.user.name%> </strong>
              </h3>

              <h3 class="event-card-title-back"><%= event.name %></h3>

              <div class="event-card-description-box">
                <p class="event-card-description">
                  <%= event.description  %>
                </p>
              </div>

              <div class="event-card-participants">
                <%= event.event_participants.count%> squad members
              </div>

              <div class="event-card-buttons">
                <a class="card-join-button" href="<%= group_event_path(event.group_id, event.id) %>">Joined</a>
                <a class="card-join-button" href="<%= group_event_path(event.group_id, event.id) %>">more details</a>
              </div>

            </div>
        </div>
  </div>



<% else %>
  <%# This is the join event button form  %>
    <%= form_for [event, event, @event_participant] do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id, class: 'card-join-hidden' %>
    <%= f.hidden_field :event_id, value: event.id, class: 'card-join-hidden' %>


  <div class="event-card" style= "height: 280px; width: 280px; font-size: 28px;">
  <%# front of the card %>
    <% if event.event_image.end_with?("jpg") %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url(event.event_image) %>)">

    <% else %>
      <div class="cover" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0)40%, rgba(0, 0, 0, 0.9)80%), url(<%= image_url eval(event.event_image)["secure_url"] %>)">
    <%end%>

            <% if event.address.present? %>
              <div class="card-address-wrapper">
                <h1 class="card-address"><i class="fa">&#xf041;</i>
                  <% first_line_of_address = event.address.split(',')[0].strip if event.address %>
                  <%= first_line_of_address %>
              </h1>
              </div>
            <% else %>
              <p> </p>
            <% end %>

        <h1 class="event-card-title">
          <%= event.name %>
        </h1>

        <h2 class="card-time-date">
          <% date = event.date %>
          <% time = event.time %>
          <%= Time.parse(date.strftime("%Y-%m-%d")).strftime("%d/%m/%y") %>,
          <%= Time.parse(time.strftime("%I:%M%P")).strftime("%I:%M%P") %>
        </h2>

        <%# back of the card %>
            <div class="card-back">

              <h3 class="event-card-host">
                <%if event.group.user.avatar.nil? %>
                  <%= image_tag "blank_avatar.jpg", class: "avatar"%>
                <%else%>
                  <%= image_tag event.group.user.avatar, class: "avatar" %>
                <%end%>
                  Hosted by <strong> <%= event.group.user.name%> </strong>
              </h3>

              <h3 class="event-card-title-back"><%= event.name %></h3>

              <div class="event-card-description-box">
                <p class="event-card-description">
                  <%= event.description  %>
                </p>
              </div>

              <div class="event-card-participants">
                <%= event.event_participants.count%> squad members
              </div>

              <div class="event-card-buttons">
                <button type="submit" class="card-join-button" >
                  <i class="fa-solid fa-dumbbell" style= "hover:fa-bounce "></i>
                </button>            
                <a class="card-join-button" href="<%= group_event_path(event.group_id, event.id) %>">more details</a>
              </div>

            </div>
      </div>
  </div>
      <% end %>
<% end %>

app/views/events/index.html.erb
<div class="">


    <div class="events-container">
        <div class="left-side-container">
    <div class="quote-container">

        <p>"Coming together is a beginning; keeping together is progress; working together is success."</p>
        <p class="quote-attribution">- Henry Ford</p>
    </div>
        <div class="block-space"></div>
<div id="event-map">
      <div style="width: 100%; height: 79vh;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
 <form class="events-calendar-position" action="/events" method="get">
              <input type="date" name="date">
              <button type="submit" class="filter-btn">
                  <i class="fas fa-search"></i> <!-- Font Awesome search icon -->
              </button>
              <button type="button" class="reset-filter-btn">
                  <i class="fas fa-undo"></i> <!-- Font Awesome reset icon -->
              </button>
          </form>
	</div>
    </div>
        <div class="block-space"></div>
        <div class="quote-container">
            <p>"Your body is your most priceless possession; you've got to take care of it!"</p>
        <p class="quote-attribution">- Arnold Schwarzenegger</p>
        </div>
        <br class="block-space">
        </div>

        <div class="right-side-container">
            <div class="quote-container">
      <h2 style= "display: flex; flex-direction: column; align-items: center;"> Upcoming Events </h2>
      </div>
            <br class="block-space">
            <% if @events.empty? %>
                <p class="no-events-msg">No events found for this date :(</p>
            <% else %>
                <div class="event-cards-grid">
                    <%= render partial: 'events/display' %>
                </div>
            <% end %>
        </div>
    </div>
  </div>
</div>

<style>

.events-container {
    display: flex;
    justify-content: space-around;
    align-items: flex-start;
    padding: 20px;
    gap: 20px;
}

.left-side-container {
    height: fit-content;
    flex: 1;
}

.right-side-container {
    flex: 1;
    margin-left: 2%;
    margin-bottom: 1%;
} */


.events-index {
    font-size: 24px;
}

.no-events-msg {
    font-style: italic;
    color: #999;
}

.events-map {
    width: 100%;
    max-width: 800px;
    max-height: 400px;
    /* Add any additional map styles here */
}

.quote-container {
    background-color: white; /* Background color with 70% opacity */
    border: 1px solid black;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}

.quote-container p {
    margin: 0; /* Remove default margin */
}

.quote-attribution {
    text-align: right; /* Align the attribution text to the right */
    font-style: italic; /* Optionally, you can style the attribution text */
    color: #888; /* Optionally, set the color */
}

.events-calendar-position {
  position: relative; /* Makes the element fixed */
  left: 3%; /* Sets the left position */
  top: 3%; /* Sets the top position */
  z-index: 1; /* Adjust the stacking order as needed */
}

.block-space{
  height: 20px;
  width: 30px;
  /* background-color: blue; */
}

.image-homepage{
  width: 100%;
  height: 50%;
}

.image-homepage img {
    width: 100%;
}
</style>

app/views/events/new.html.erb
<br>
<div class="container form-border-generic" style="max-width: 75%">

<h1>create event page </h1>
<%= simple_form_for([@group, @event], html: { :class => "form-inline" }) do |f| %>
  <% if @event.errors.any? %>
    <h2><%= pluralize(@event.errors.count, "error") %> prevented this Event from saving:</h2>
    <ul>
      <% @event.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time %>
    <%= f.time_field :time, class: "form-control" %>
  </div>

    <div class="form-group">
    <%= f.label :activity %>
    <%= f.select :activity_id, Activity.all.collect { |a| [a.name, a.id] }, { include_blank: true }, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :event_image, as: :file, class: "form-control" %>
  </div>

  <div class="form_group">
    <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none form-control" },
        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  </div>

<%= f.hidden_field :group_id, value: params[:group_id] %>
<%= f.hidden_field :user_id, value: params[current_user.id] %>
<br>

  <div class="form-group">
    <%= f.submit "Create Event", class: "btn btn-primary"%>
  </div>
<% end %>
<br>
</div>

app/views/events/search.html.erb
<div class="">


    <div class="events-container">
        <div class="left-side-container">
    <div class="quote-container">

        <p>"Coming together is a beginning; keeping together is progress; working together is success."</p>
        <p class="quote-attribution">- Henry Ford</p>
    </div>
        <div class="block-space"></div>
            <div class="image-homepage">
            <% @image = "#{@query.capitalize}_group.jpg"%>
                <% if @image.end_with?("jpg") %>
                    <%=image_tag @image %>
                <% else %>
                    <%= image_tag eval(@image)["url"] %>
                <% end %>
            </div>
        <div class="block-space"></div>
        <div class="quote-container">
            <p>"Your body is your most priceless possession; you've got to take care of it!"</p>
        <p class="quote-attribution">- Arnold Schwarzenegger</p>
        </div>
        <br class="block-space">
        </div>

         <div class="right-side-container">
            <div class="quote-container">
      <h2>Upcoming Events for <%= @query.capitalize %></h2>
      </div>
            <br class="block-space">
            <% if @events.empty? %>
                <p class="no-events-msg">No events found for your search query :(</p>
            <% else %>
                <div class="event-cards-grid">
                    <%= render partial: 'events/display' %>
                </div>
            <% end %>
        </div>
    </div>
  </div>
</div>

<style>
.events-container {
    display: flex;
    justify-content: space-around;
    align-items: flex-start;
    padding: 20px;
    gap: 20px;
}

.left-side-container {
    height: fit-content;
    flex: 1;
}

.right-side-container {
    flex: 1;
    margin-left: 2%;
    margin-bottom: 1%;
} */


.events-index {
    font-size: 24px;
}

.no-events-msg {
    font-style: italic;
    color: #999;
}

.events-map {
    width: 100%;
    max-width: 800px;
    max-height: 400px;
    /* Add any additional map styles here */
}

.quote-container {
    background-color: white; /* Background color with 70% opacity */
    border: 1px solid black;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}

.quote-container p {
    margin: 0; /* Remove default margin */
}

.quote-attribution {
    text-align: right; /* Align the attribution text to the right */
    font-style: italic; /* Optionally, you can style the attribution text */
    color: #888; /* Optionally, set the color */
}

.events-calendar-position {
  position: relative; /* Makes the element fixed */
  left: 3%; /* Sets the left position */
  top: 3%; /* Sets the top position */
  z-index: 10; /* Adjust the stacking order as needed */
}

.block-space{
  height: 20px;
  width: 30px;
  /* background-color: blue; */
}

.image-homepage{
  width: 100%;
  height: 50%;
}

.image-homepage img {
    width: 100%;
}
</style>

app/views/events/show.html.erb
<div id="container">
<%# Host and participants sections %>
  <div id="event-show-host-and-participants">
    <div id="event-show-host">
      <%if @event.group.user.avatar.nil?%>
        <%=image_tag "blank_avatar.jpg", style: "margin: 4px;", class: "avatar-bordered"%>
      <%else%>
        <%= image_tag @event.group.user.avatar, style: "margin: 4px;", class: "avatar-bordered" %>
      <%end%>
      <h2>Hosted by <%= @event.group.user.name %></h2>
      <div class="action-button">
        <div id="group-index-above-group-right-section-buttons">
          <div class="button-container">
          <a href="<%= group_path(@group) %>" class="action-button">  View Squad </a>
          <%link_to group_path(@group) %>
            <div class="white-border-effect"></div>
          </div>
        </div>
      </div>
    </div>
    <div id="event-show-participants">
      <% @event_participants.each do |participant| %>
        <% if participant.user.avatar.nil?%>
          <%= image_tag "blank_avatar.jpg", style: "margin: 4px;", class: "avatar"%>
          <p class="hide"><%=participant.user.name%></p>
        <% else %>
          <%= image_tag participant.user.avatar,style: "margin: 4px;", class: "avatar" %>
          <p class="hide"><%=participant.user.name%></p>
        <% end %>
      <% end %>
    </div>
  </div>
  <hr>
<%# below host and participant line break %>

  <div id="event-show-left-and-rigth-section">
<%# left section with event image, event info and join button %>
    <div id="event-show-left-section">
      <div id="event-show-left-section-image">
        <% if @event.event_image.end_with?("jpg") %>
          <%=image_tag @event.event_image, width: 500, height: 350 %>
        <% else %>
          <%= image_tag eval(@event.event_image)["url"], width: 300, height: 200 %>
        <% end %>
      </div>
      <div id="event-show-left-section-name-timedate-and-button">
      <div id="event-show-left-section-name-timedate">
        <div id="event-show-left-section-name">
          <h2><%= @event.name %></h2>
        </div>
        <div id="event-show-left-section-time-date">
            <% date = @event.date %>
            <% time = @event.time %>
            <h4><%= Time.parse(date.strftime("%Y-%m-%d")).strftime("%d/%m/%y") %>   <%= Time.parse(time.strftime("%I:%M%P")).strftime("%I:%M%P") %></h4>
        </div>
        <div id="event-show-event-participant-count">
          <h5> <%= @event_participants.count  %> Squad members participating</h5>
        </div>
      </div>
        <div id="event-show-left-section-button">
          <%= render partial: 'event_participants/form' %>
        </div>
      </div>
      <div id="event-show-description">
      <p> <%= @event.description %></p>
      </div>
    </div>
  <%# event show right section ,map and chat %>
    <div id="event-show-rigth-section">

    <div id="event-show-map-right-section">
      <div style="width: 100%; height: 40vh;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    </div>


    <div id="event-show-chatroom-input-right-section-">
  <h2>Event Chatroom for <%= @chatroom.name %></h2>
  <hr>
  <%= simple_form_for [@group, @event, @chatroom, @message], url: event_chatroom_messages_path(@event, @chatroom),
    html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
  %>
    <%= f.input :content,
      label: false,
      placeholder: "Message ##{@chatroom.name}",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send",style: "height: 5vh;", class: "custom-search-button" %>
  <% end %>
  <div id="event-show-chatroom-right-section">
    <%= render partial: 'chatrooms/show', locals: { event: @event } %>
  </div>
</div>
</div>
</div>
</div>