config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "events#index"
  get 'my_groups', to: 'groups#my_groups', as: :my_groups

  resources :groups do
    resources :group_participants
    resources :events
  end

  resources :events, only: [:index, :show] do
    collection do
      get 'search'
    end
    resources :event_participants, as: 'participants'
    post 'events/:event_id/event_participants', to: 'event_participants#create', as: 'event_event_participants'
    delete '/events/:event_id/event_participants/:id', to: 'event_participants#destroy'
    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  get 'about', to: 'pages#about'
  get 'terms-and-conditions', to: 'pages#tandc'
  get 'privacy-policy', to: 'pages#private'
  get 'contact-us', to: 'pages#contact'
  get 'cookies-policy', to: 'pages#cookies'



  resources :users, only: [] do
    resources :workout_preferences
    post 'generate_workout_plan', to: 'workout_preferences#generate_workout_plan'
  end
end

app/models/event_participant.rb
class EventParticipant < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/controllers/event_participants_controller.rb
class EventParticipantsController < ApplicationController

  def event_path(event)
    # event_id is the ID of the event
    event_id = event.id

    # Generate the path to the event page
    path = "/events/#{event_id}"

    # Return the path
    return path
  end

  def index
    @event_participants = EventParticipant.all
  end

  def show
    @event = Event.find(params[:event_id])
    if @event.present?
      @event_participant = EventParticipant.find(params[:id])
      if @event_participant.user_id == current_user.id
        @event_participant.destroy
        redirect_to event_path(@event), notice: "You have left the event."
      else
        redirect_to event_path(@event), alert: "You are not authorized to leave this event."
      end
    else
      redirect_to events_path, alert: "Event not found."
    end
  end

  def new
    @event_participant = EventParticipant.new
  end

  def create
    event_id = params[:event_participant][:event_id] # Adjust this based on your form field name

    @event = Event.find(event_id)
    @event_participant = EventParticipant.new(user_id: current_user.id, event_id: event_id)

    if @event_participant.save
      if request.referer == root_url # Check if the referer is the root page
        redirect_to root_path, notice: "Successfully joined the event!"
      elsif Rails.application.routes.recognize_path(request.fullpath)[:controller] == 'your_controller_name' && Rails.application.routes.recognize_path(request.fullpath)[:action] == 'your_action_name'
        redirect_to search_event_path(@event_participant.event), notice: "Successfully joined the event!"
      else
        redirect_to event_path(@event_participant.event), notice: "Successfully joined the event!"
      end
    else
      flash[:alert] = "You did not join."
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @event_participant = EventParticipant.find(params[:id])

    if @event_participant.update(event_participant_params)
      redirect_to event_path(@event)
    else
      render 'events/show' # Render the show page with errors if the update fails
    end
  end

  def destroy
    @event_participant = EventParticipant.find(params[:id])

    if current_user == @event_participant.user
      @event_participant.destroy
      redirect_to event_path(@event), notice: "Successfully left the event!"
    else
      redirect_to event_path(@event), alert: "You can't leave this event."
    end
  end

  def event_participant_params
    params.require(:event_participant).permit(:user_id, :event_id)
  end
end

app/views/event_participants/_form.html.erb
<% if @event.group.user_id == current_user.id %>
  <%# <h2>YOU ARE The President!</h2> %>
<%= button_to "Delete Event", group_event_path(@group, @event), method: :delete, data: { turbo_confirm: 'Are you sure?' } %>
    <% if flash[:notice].present? %>
      <div class="alert alert-success">
      <%= flash[:notice] %>
      </div>
      <% end %>

    <% if flash[:alert].present? %>
      <div class="alert alert-danger">
      <%= flash[:alert] %>
      </div>
    <% end %>
<% elsif @existing_participant %>
  <%# <h2>you are part of the event Squad!</h2> %>
  <div class="button-container">
  <div class="secondary-squads-button" id="leave-group">
    <%= link_to "Leave Event", event_participant_path(@event, @existing_participant), method: :delete, data: { turbo_confirm: 'Are you sure?' } %>
  </div>  
    <div class="black-border-effect" id=""></div>
  </div>
    <% if flash[:notice].present? %>
      <div class="alert alert-success">
      <%= flash[:notice] %>
      </div>
      <% end %>

    <% if flash[:alert].present? %>
      <div class="alert alert-danger">
      <%= flash[:alert] %>
      </div>
    <% end %>
<% else %>
<%= form_for [@event, @event, @event_participant] do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :event_id, value: @event.id %>
<div class="button-container">
    <input class="main-squads-button" id="events-join" type="submit" name="commit" value="Join" data-disable-with="Join">
    <div class="black-border-effect" id="events-join-border"></div>
</div>

<% end %>

<% end %>

app/views/event_participants/_join.html.erb
<% @event_participants.each do |participant| %>
  <p>User ID: <%= participant.user.id %></p>
  <p>Email: <%= participant.user.email %></p>
  <p>Name: <%= participant.user.name %></p>
  <%if participant.user.avatar.nil?%>
<p>Avatar<%= image_tag "blank_avatar.jpg", class: "avatar"%>  </p>
    <%else%>
    <p>Avatar: <%= image_tag participant.user.avatar, class: "avatar" %></p>
  </p>
  <hr>
<% end %>
<% end %>